export const BookData = [
    {
        id: 0,
        book_name: "50 Shades of Grey",
        book_description: "For all the trappings of success—his multinational businesses, his vast wealth, his loving family—Grey is a man tormented by demons and consumed by the need to control. When the couple embarks on a daring, passionately physical affair, Ana discovers Christian Grey's secrets and explores her own dark desires.",
        book_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTtReeVL3deNAH5GDsz34UFgbNmY4eWcVXc-Zuj1xl_W1Tt5HhI",
        print_length: "354 pages",
        language: "English",
        author_name: "E.L.James",
        price: "300",
    },
    {
        id: 1,
        book_name: "After",
        book_description: "After is a 2019 American romantic drama film about a young woman who falls for a mysterious rebel with a dark secret",
        book_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTlYKiNITrsdFld2oE-kTiJ8DobBZ5eXaC_xThACYGI9bKjxnM0",
        print_length: "361 pages",
        language: "English",
        author_name: "Anna Todd",
        price: "320",
    },
    {
        id: 2,
        book_name: "Five Feets Apart",
        book_description: "Five Feet Apart is a romantic, heart-rending drama about doomed young love. It highlights the plight of patients living with cystic fibrosis and will appeal to adult and teenage audiences.",
        book_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRx_GGPsTuTRPfA-c48FsI1zC2XEfLq_-Kx23THCkDg7hXxQ3vv",
        print_length: "340 pages",
        language: "English",
        author_name: "Rachael Lippincott",
        price: "370",
    },
    {
        id: 3,
        book_name: "It Ends With Us",
        book_description: "The book's publisher described it as a story about a workaholic with a too-good-to-be-true romance who can't stop thinking about her first love.",
        book_url: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ8Sun1prLxrmmWO8rmaqFc6NtRLKa0AwIesi7WClue82spRvQN",
        print_length: "342 pages",
        language: "English",
        author_name: "Colleen Hoover",
        price: "365",
    },
    {
        id: 4,
        book_name: "Me Before You",
        book_description: "Me Before You is a book by Jojo Moyes about a young woman who becomes the caregiver for a paralyzed man and the unlikely bond they form.",
        book_url: "https://m.media-amazon.com/images/I/914woZe6eBL._AC_UF1000,1000_QL80_.jpg",
        print_length: "315 pages",
        language: "English",
        author_name: "Jojo Moyes",
        price: "320",
    },
    {
        id: 5,
        book_name: "The Vow",
        book_description: "The film is about Paige and Leo Collins, who are in a car accident and rushed to the emergency room. The movie interweaves scenes from their courtship, engagement, and wedding with the present.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6ZCjfMNEgXLPdC2AfS7J0AZfDMm8XutTBUQ&s",
        print_length: "343 pages",
        language: "English",
        author_name: "Kim Carpenter",
        price: "350",
    },
    {
        id: 6,
        book_name: "Work It",
        book_description: "Synopsis An awkward 18-year-old achieves near-perfection by sheer hard work. She vows to transform her gawkiness through dance, and refine her skills until she competes at a competition.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPWUITrd-QiKdXb8ZkL0THJWU4hFu8HMxaSG8CuN0hrEI737VbZdcjoKEZqAzV3aJOag&usqp=CAU",
        print_length: "250 pages",
        language: "English",
        author_name: "Alison Peck",
        price: "230",
    },
    {
        id: 7,
        book_name: "Kissing Booth",
        book_description: "The Kissing Booth is a 2018 romantic comedy film about a high school student who develops a secret crush on her best friend's older brother.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCJMGj8KjsBsIR5sAT7OMhw8Lo4ZFeXZR1bg&s",
        print_length: "350 pages",
        language: "English",
        author_name: "Beth Reekles",
        price: "370",
    },
    {
        id: 8,
        book_name: "Enola Holmes",
        book_description: "Enola Holmes is the youngest sibling in the Holmes family. She is extremely intelligent, observant, and insightful, defying the social norms for women of the time.",
        book_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsIQxrfrWP7zThrCKA1-8XSb9x6ynZsXTbYQ&s",
        print_length: "340 pages",
        language: "English",
        author_name: "Nancy Springer",
        price: "350",
    },
    {
        id: 9,
        book_name: "The Royal Treatment",
        book_description: "Enola Holmes is the youngest sibling in the Holmes family. She is extremely intelligent, observant, and insightful, defying the social norms for women of the time.",
        book_url: "https://upload.wikimedia.org/wikipedia/en/4/42/The_Royal_Treatment.jpg",
        print_length: "333 pages",
        language: "English",
        author_name: "Melanie Summers",
        price: "300",
    }
]